# nombre  app
spring.application.name=APICONS
server.port=8080

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,env
management.endpoint.health.show-details=when_authorized

# Thymeleaf
spring.thymeleaf.cache=false

# JPA
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Perfil por defecto
spring.profiles.active=local
