# Base de datos local PostgreSQL (sin SSL)
spring.datasource.url=jdbc:postgresql://localhost:5432/cons_apis
spring.datasource.username=user_apis
spring.datasource.password=Ap1Consum02018.*
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect