# Ejemplo cloud con SSL (ajusta cuando tengas la instancia real)
spring.datasource.url=jdbc:postgresql://tu-host-cloud:5432/cons_apis?sslmode=require
spring.datasource.username=user_apis
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
